name: trump-timeline
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - pip:
    - requests
    - beautifulsoup4
    - python-dateutil 